name: William Rants
favicon: null
layout_spectrum: 0.7782960357144475
typography_spectrum: 0.862004908034578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5340793880168349
  lightness: 0.35401265206746757
  saturation: 0.8622987465932965
  rhythmicContrast: 0.7134352459106594
purpose: []
